/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_song_token1 = 1,
  anon_sym_LBRACK = 2,
  anon_sym_RBRACK = 3,
  sym_section_name = 4,
  sym_frontmatter_delimiter = 5,
  anon_sym_COLON = 6,
  sym_frontmatter_key = 7,
  sym_quoted_string = 8,
  sym_unquoted_value = 9,
  sym_simile_mark = 10,
  sym_dot = 11,
  sym_open_barline = 12,
  sym_close_barline = 13,
  anon_sym_LPAREN = 14,
  anon_sym_SLASH = 15,
  anon_sym_RPAREN = 16,
  sym_integer = 17,
  sym_note_letter = 18,
  sym_accidental = 19,
  sym_quality = 20,
  sym_song = 21,
  sym_section_label = 22,
  sym_frontmatter = 23,
  sym_frontmatter_field = 24,
  sym_frontmatter_value = 25,
  sym_row = 26,
  sym_bar_tail = 27,
  sym_beat_slot = 28,
  sym_time_signature = 29,
  sym_chord = 30,
  aux_sym_song_repeat1 = 31,
  aux_sym_frontmatter_repeat1 = 32,
  aux_sym_row_repeat1 = 33,
  aux_sym_bar_tail_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_song_token1] = "song_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_section_name] = "section_name",
  [sym_frontmatter_delimiter] = "frontmatter_delimiter",
  [anon_sym_COLON] = ":",
  [sym_frontmatter_key] = "frontmatter_key",
  [sym_quoted_string] = "quoted_string",
  [sym_unquoted_value] = "unquoted_value",
  [sym_simile_mark] = "simile_mark",
  [sym_dot] = "dot",
  [sym_open_barline] = "open_barline",
  [sym_close_barline] = "close_barline",
  [anon_sym_LPAREN] = "(",
  [anon_sym_SLASH] = "/",
  [anon_sym_RPAREN] = ")",
  [sym_integer] = "integer",
  [sym_note_letter] = "note_letter",
  [sym_accidental] = "accidental",
  [sym_quality] = "quality",
  [sym_song] = "song",
  [sym_section_label] = "section_label",
  [sym_frontmatter] = "frontmatter",
  [sym_frontmatter_field] = "frontmatter_field",
  [sym_frontmatter_value] = "frontmatter_value",
  [sym_row] = "row",
  [sym_bar_tail] = "bar_tail",
  [sym_beat_slot] = "beat_slot",
  [sym_time_signature] = "time_signature",
  [sym_chord] = "chord",
  [aux_sym_song_repeat1] = "song_repeat1",
  [aux_sym_frontmatter_repeat1] = "frontmatter_repeat1",
  [aux_sym_row_repeat1] = "row_repeat1",
  [aux_sym_bar_tail_repeat1] = "bar_tail_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_song_token1] = aux_sym_song_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_section_name] = sym_section_name,
  [sym_frontmatter_delimiter] = sym_frontmatter_delimiter,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_frontmatter_key] = sym_frontmatter_key,
  [sym_quoted_string] = sym_quoted_string,
  [sym_unquoted_value] = sym_unquoted_value,
  [sym_simile_mark] = sym_simile_mark,
  [sym_dot] = sym_dot,
  [sym_open_barline] = sym_open_barline,
  [sym_close_barline] = sym_close_barline,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_integer] = sym_integer,
  [sym_note_letter] = sym_note_letter,
  [sym_accidental] = sym_accidental,
  [sym_quality] = sym_quality,
  [sym_song] = sym_song,
  [sym_section_label] = sym_section_label,
  [sym_frontmatter] = sym_frontmatter,
  [sym_frontmatter_field] = sym_frontmatter_field,
  [sym_frontmatter_value] = sym_frontmatter_value,
  [sym_row] = sym_row,
  [sym_bar_tail] = sym_bar_tail,
  [sym_beat_slot] = sym_beat_slot,
  [sym_time_signature] = sym_time_signature,
  [sym_chord] = sym_chord,
  [aux_sym_song_repeat1] = aux_sym_song_repeat1,
  [aux_sym_frontmatter_repeat1] = aux_sym_frontmatter_repeat1,
  [aux_sym_row_repeat1] = aux_sym_row_repeat1,
  [aux_sym_bar_tail_repeat1] = aux_sym_bar_tail_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_song_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter_delimiter] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_frontmatter_key] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_value] = {
    .visible = true,
    .named = true,
  },
  [sym_simile_mark] = {
    .visible = true,
    .named = true,
  },
  [sym_dot] = {
    .visible = true,
    .named = true,
  },
  [sym_open_barline] = {
    .visible = true,
    .named = true,
  },
  [sym_close_barline] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_note_letter] = {
    .visible = true,
    .named = true,
  },
  [sym_accidental] = {
    .visible = true,
    .named = true,
  },
  [sym_quality] = {
    .visible = true,
    .named = true,
  },
  [sym_song] = {
    .visible = true,
    .named = true,
  },
  [sym_section_label] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter_field] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter_value] = {
    .visible = true,
    .named = true,
  },
  [sym_row] = {
    .visible = true,
    .named = true,
  },
  [sym_bar_tail] = {
    .visible = true,
    .named = true,
  },
  [sym_beat_slot] = {
    .visible = true,
    .named = true,
  },
  [sym_time_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_chord] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_song_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_frontmatter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_row_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bar_tail_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '"', 5,
        '%', 35,
        '(', 45,
        ')', 47,
        '-', 52,
        '.', 36,
        '/', 46,
        '7', 56,
        ':', 31,
        'M', 12,
        '[', 26,
        ']', 27,
        'd', 13,
        'm', 54,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(22);
      if (lookahead == '#' ||
          lookahead == 'b') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'G')) ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '-', 51,
        '.', 36,
        '7', 55,
        ':', 19,
        'M', 12,
        'd', 13,
        'm', 54,
        '|', 43,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(10);
      if (lookahead == '#' ||
          lookahead == 'b') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'G')) ADVANCE(49);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == '|') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'G')) ADVANCE(49);
      END_STATE();
    case 11:
      if (lookahead == '5') ADVANCE(51);
      END_STATE();
    case 12:
      if (lookahead == '7') ADVANCE(51);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'j') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(53);
      END_STATE();
    case 16:
      if (lookahead == '|') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == '|') ADVANCE(41);
      END_STATE();
    case 18:
      if (lookahead == '|') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == '|') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(29);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 22:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '"', 5,
        '%', 35,
        '(', 45,
        ')', 47,
        '-', 6,
        '.', 36,
        '/', 46,
        ':', 31,
        '[', 26,
        ']', 27,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(22);
      if (('A' <= lookahead && lookahead <= 'G')) ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '%', 35,
        '(', 45,
        '-', 6,
        '.', 36,
        ':', 18,
        '[', 26,
        '|', 39,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(23);
      if (('A' <= lookahead && lookahead <= 'G')) ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_song_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_frontmatter_delimiter);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_frontmatter_key);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_simile_mark);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_dot);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_open_barline);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_open_barline);
      if (lookahead == ':') ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_open_barline);
      if (lookahead == '|') ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_close_barline);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_close_barline);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == 'x') ADVANCE(21);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_close_barline);
      if (lookahead == ':') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_close_barline);
      if (lookahead == '|') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_close_barline);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(40);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_note_letter);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_accidental);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_quality);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_quality);
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_quality);
      if (lookahead == '7') ADVANCE(51);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_quality);
      if (lookahead == '7') ADVANCE(55);
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_quality);
      if (lookahead == 'b') ADVANCE(11);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_quality);
      if (lookahead == 'b') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 23},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 23},
  [6] = {.lex_state = 23},
  [7] = {.lex_state = 23},
  [8] = {.lex_state = 23},
  [9] = {.lex_state = 23},
  [10] = {.lex_state = 23},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 23},
  [19] = {.lex_state = 23},
  [20] = {.lex_state = 23},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 23},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 20},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 23},
  [39] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_song_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_frontmatter_delimiter] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_simile_mark] = ACTIONS(1),
    [sym_dot] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_note_letter] = ACTIONS(1),
    [sym_accidental] = ACTIONS(1),
    [sym_quality] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_song] = STATE(35),
    [sym_section_label] = STATE(9),
    [sym_frontmatter] = STATE(10),
    [sym_row] = STATE(9),
    [aux_sym_song_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_song_token1] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_frontmatter_delimiter] = ACTIONS(9),
    [sym_open_barline] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(15), 1,
      sym_simile_mark,
    ACTIONS(17), 1,
      sym_dot,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_note_letter,
    STATE(15), 1,
      sym_time_signature,
    STATE(23), 1,
      sym_chord,
    STATE(3), 2,
      sym_bar_tail,
      aux_sym_row_repeat1,
    STATE(11), 2,
      sym_beat_slot,
      aux_sym_bar_tail_repeat1,
    ACTIONS(13), 4,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      anon_sym_LBRACK,
      sym_open_barline,
  [33] = 9,
    ACTIONS(25), 1,
      sym_simile_mark,
    ACTIONS(28), 1,
      sym_dot,
    ACTIONS(31), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      sym_note_letter,
    STATE(15), 1,
      sym_time_signature,
    STATE(23), 1,
      sym_chord,
    STATE(3), 2,
      sym_bar_tail,
      aux_sym_row_repeat1,
    STATE(11), 2,
      sym_beat_slot,
      aux_sym_bar_tail_repeat1,
    ACTIONS(23), 4,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      anon_sym_LBRACK,
      sym_open_barline,
  [66] = 8,
    ACTIONS(15), 1,
      sym_simile_mark,
    ACTIONS(17), 1,
      sym_dot,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_note_letter,
    STATE(15), 1,
      sym_time_signature,
    STATE(23), 1,
      sym_chord,
    STATE(2), 2,
      sym_bar_tail,
      aux_sym_row_repeat1,
    STATE(11), 2,
      sym_beat_slot,
      aux_sym_bar_tail_repeat1,
  [93] = 1,
    ACTIONS(37), 8,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      anon_sym_LBRACK,
      sym_simile_mark,
      sym_dot,
      sym_open_barline,
      anon_sym_LPAREN,
      sym_note_letter,
  [104] = 1,
    ACTIONS(39), 8,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      anon_sym_LBRACK,
      sym_simile_mark,
      sym_dot,
      sym_open_barline,
      anon_sym_LPAREN,
      sym_note_letter,
  [115] = 5,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      aux_sym_song_token1,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      sym_open_barline,
    STATE(7), 3,
      sym_section_label,
      sym_row,
      aux_sym_song_repeat1,
  [133] = 5,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_open_barline,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      aux_sym_song_token1,
    STATE(7), 3,
      sym_section_label,
      sym_row,
      aux_sym_song_repeat1,
  [151] = 5,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_open_barline,
    ACTIONS(54), 1,
      aux_sym_song_token1,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    STATE(7), 3,
      sym_section_label,
      sym_row,
      aux_sym_song_repeat1,
  [169] = 5,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_open_barline,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      aux_sym_song_token1,
    STATE(8), 3,
      sym_section_label,
      sym_row,
      aux_sym_song_repeat1,
  [187] = 5,
    ACTIONS(17), 1,
      sym_dot,
    ACTIONS(21), 1,
      sym_note_letter,
    ACTIONS(60), 1,
      sym_close_barline,
    STATE(23), 1,
      sym_chord,
    STATE(12), 2,
      sym_beat_slot,
      aux_sym_bar_tail_repeat1,
  [204] = 5,
    ACTIONS(62), 1,
      sym_dot,
    ACTIONS(65), 1,
      sym_close_barline,
    ACTIONS(67), 1,
      sym_note_letter,
    STATE(23), 1,
      sym_chord,
    STATE(12), 2,
      sym_beat_slot,
      aux_sym_bar_tail_repeat1,
  [221] = 5,
    ACTIONS(17), 1,
      sym_dot,
    ACTIONS(21), 1,
      sym_note_letter,
    ACTIONS(70), 1,
      sym_close_barline,
    STATE(23), 1,
      sym_chord,
    STATE(12), 2,
      sym_beat_slot,
      aux_sym_bar_tail_repeat1,
  [238] = 3,
    ACTIONS(74), 1,
      sym_accidental,
    ACTIONS(76), 1,
      sym_quality,
    ACTIONS(72), 3,
      sym_dot,
      sym_close_barline,
      sym_note_letter,
  [250] = 4,
    ACTIONS(17), 1,
      sym_dot,
    ACTIONS(21), 1,
      sym_note_letter,
    STATE(23), 1,
      sym_chord,
    STATE(13), 2,
      sym_beat_slot,
      aux_sym_bar_tail_repeat1,
  [264] = 3,
    ACTIONS(78), 1,
      sym_frontmatter_delimiter,
    ACTIONS(80), 1,
      sym_frontmatter_key,
    STATE(17), 2,
      sym_frontmatter_field,
      aux_sym_frontmatter_repeat1,
  [275] = 3,
    ACTIONS(80), 1,
      sym_frontmatter_key,
    ACTIONS(82), 1,
      sym_frontmatter_delimiter,
    STATE(21), 2,
      sym_frontmatter_field,
      aux_sym_frontmatter_repeat1,
  [286] = 1,
    ACTIONS(84), 4,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      anon_sym_LBRACK,
      sym_open_barline,
  [293] = 1,
    ACTIONS(86), 4,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      anon_sym_LBRACK,
      sym_open_barline,
  [300] = 1,
    ACTIONS(88), 4,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      anon_sym_LBRACK,
      sym_open_barline,
  [307] = 3,
    ACTIONS(90), 1,
      sym_frontmatter_delimiter,
    ACTIONS(92), 1,
      sym_frontmatter_key,
    STATE(21), 2,
      sym_frontmatter_field,
      aux_sym_frontmatter_repeat1,
  [318] = 2,
    ACTIONS(97), 1,
      sym_quality,
    ACTIONS(95), 3,
      sym_dot,
      sym_close_barline,
      sym_note_letter,
  [327] = 1,
    ACTIONS(99), 3,
      sym_dot,
      sym_close_barline,
      sym_note_letter,
  [333] = 2,
    STATE(36), 1,
      sym_frontmatter_value,
    ACTIONS(101), 2,
      sym_quoted_string,
      sym_unquoted_value,
  [341] = 1,
    ACTIONS(103), 3,
      sym_dot,
      sym_close_barline,
      sym_note_letter,
  [347] = 1,
    ACTIONS(95), 3,
      sym_dot,
      sym_close_barline,
      sym_note_letter,
  [353] = 1,
    ACTIONS(105), 2,
      sym_frontmatter_delimiter,
      sym_frontmatter_key,
  [358] = 1,
    ACTIONS(107), 2,
      sym_dot,
      sym_note_letter,
  [363] = 1,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
  [367] = 1,
    ACTIONS(111), 1,
      anon_sym_COLON,
  [371] = 1,
    ACTIONS(113), 1,
      sym_integer,
  [375] = 1,
    ACTIONS(60), 1,
      sym_close_barline,
  [379] = 1,
    ACTIONS(115), 1,
      sym_section_name,
  [383] = 1,
    ACTIONS(117), 1,
      anon_sym_SLASH,
  [387] = 1,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
  [391] = 1,
    ACTIONS(121), 1,
      aux_sym_song_token1,
  [395] = 1,
    ACTIONS(123), 1,
      aux_sym_song_token1,
  [399] = 1,
    ACTIONS(125), 1,
      sym_integer,
  [403] = 1,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 104,
  [SMALL_STATE(7)] = 115,
  [SMALL_STATE(8)] = 133,
  [SMALL_STATE(9)] = 151,
  [SMALL_STATE(10)] = 169,
  [SMALL_STATE(11)] = 187,
  [SMALL_STATE(12)] = 204,
  [SMALL_STATE(13)] = 221,
  [SMALL_STATE(14)] = 238,
  [SMALL_STATE(15)] = 250,
  [SMALL_STATE(16)] = 264,
  [SMALL_STATE(17)] = 275,
  [SMALL_STATE(18)] = 286,
  [SMALL_STATE(19)] = 293,
  [SMALL_STATE(20)] = 300,
  [SMALL_STATE(21)] = 307,
  [SMALL_STATE(22)] = 318,
  [SMALL_STATE(23)] = 327,
  [SMALL_STATE(24)] = 333,
  [SMALL_STATE(25)] = 341,
  [SMALL_STATE(26)] = 347,
  [SMALL_STATE(27)] = 353,
  [SMALL_STATE(28)] = 358,
  [SMALL_STATE(29)] = 363,
  [SMALL_STATE(30)] = 367,
  [SMALL_STATE(31)] = 371,
  [SMALL_STATE(32)] = 375,
  [SMALL_STATE(33)] = 379,
  [SMALL_STATE(34)] = 383,
  [SMALL_STATE(35)] = 387,
  [SMALL_STATE(36)] = 391,
  [SMALL_STATE(37)] = 395,
  [SMALL_STATE(38)] = 399,
  [SMALL_STATE(39)] = 403,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_song, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bar_tail, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bar_tail, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_song_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_song_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_song_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_song_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_song, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_song, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bar_tail_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bar_tail_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bar_tail_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_label, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_frontmatter_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_frontmatter_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_beat_slot, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter_field, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_signature, 5, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [119] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter_value, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_grigson(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "grigson",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
