/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_song_token1 = 1,
  sym_frontmatter_delimiter = 2,
  anon_sym_COLON = 3,
  sym_frontmatter_key = 4,
  sym_frontmatter_value = 5,
  sym_barline = 6,
  anon_sym_LPAREN = 7,
  anon_sym_SLASH = 8,
  anon_sym_RPAREN = 9,
  sym_integer = 10,
  sym_note_letter = 11,
  sym_accidental = 12,
  sym_quality = 13,
  sym_song = 14,
  sym_frontmatter = 15,
  sym_frontmatter_field = 16,
  sym_row = 17,
  sym_bar_tail = 18,
  sym_time_signature = 19,
  sym_chord = 20,
  aux_sym_song_repeat1 = 21,
  aux_sym_frontmatter_repeat1 = 22,
  aux_sym_row_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_song_token1] = "song_token1",
  [sym_frontmatter_delimiter] = "frontmatter_delimiter",
  [anon_sym_COLON] = ":",
  [sym_frontmatter_key] = "frontmatter_key",
  [sym_frontmatter_value] = "frontmatter_value",
  [sym_barline] = "barline",
  [anon_sym_LPAREN] = "(",
  [anon_sym_SLASH] = "/",
  [anon_sym_RPAREN] = ")",
  [sym_integer] = "integer",
  [sym_note_letter] = "note_letter",
  [sym_accidental] = "accidental",
  [sym_quality] = "quality",
  [sym_song] = "song",
  [sym_frontmatter] = "frontmatter",
  [sym_frontmatter_field] = "frontmatter_field",
  [sym_row] = "row",
  [sym_bar_tail] = "bar_tail",
  [sym_time_signature] = "time_signature",
  [sym_chord] = "chord",
  [aux_sym_song_repeat1] = "song_repeat1",
  [aux_sym_frontmatter_repeat1] = "frontmatter_repeat1",
  [aux_sym_row_repeat1] = "row_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_song_token1] = aux_sym_song_token1,
  [sym_frontmatter_delimiter] = sym_frontmatter_delimiter,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_frontmatter_key] = sym_frontmatter_key,
  [sym_frontmatter_value] = sym_frontmatter_value,
  [sym_barline] = sym_barline,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_integer] = sym_integer,
  [sym_note_letter] = sym_note_letter,
  [sym_accidental] = sym_accidental,
  [sym_quality] = sym_quality,
  [sym_song] = sym_song,
  [sym_frontmatter] = sym_frontmatter,
  [sym_frontmatter_field] = sym_frontmatter_field,
  [sym_row] = sym_row,
  [sym_bar_tail] = sym_bar_tail,
  [sym_time_signature] = sym_time_signature,
  [sym_chord] = sym_chord,
  [aux_sym_song_repeat1] = aux_sym_song_repeat1,
  [aux_sym_frontmatter_repeat1] = aux_sym_frontmatter_repeat1,
  [aux_sym_row_repeat1] = aux_sym_row_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_song_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_frontmatter_delimiter] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_frontmatter_key] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter_value] = {
    .visible = true,
    .named = true,
  },
  [sym_barline] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_note_letter] = {
    .visible = true,
    .named = true,
  },
  [sym_accidental] = {
    .visible = true,
    .named = true,
  },
  [sym_quality] = {
    .visible = true,
    .named = true,
  },
  [sym_song] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter_field] = {
    .visible = true,
    .named = true,
  },
  [sym_row] = {
    .visible = true,
    .named = true,
  },
  [sym_bar_tail] = {
    .visible = true,
    .named = true,
  },
  [sym_time_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_chord] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_song_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_frontmatter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_row_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 17,
        '\r', 1,
        '(', 24,
        ')', 26,
        '-', 6,
        '/', 25,
        '7', 34,
        ':', 19,
        'M', 8,
        'd', 10,
        'm', 32,
        '|', 23,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(15);
      if (lookahead == '#' ||
          lookahead == 'b') ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'G')) ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '5') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == '7') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == '7') ADVANCE(30);
      if (lookahead == 'M') ADVANCE(8);
      if (lookahead == 'd') ADVANCE(10);
      if (lookahead == 'm') ADVANCE(32);
      if (lookahead == '|') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(13);
      if (lookahead == '#' ||
          lookahead == 'b') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'j') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == '|') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(13);
      END_STATE();
    case 14:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 17,
        '\r', 1,
        '(', 24,
        ')', 26,
        '-', 6,
        '/', 25,
        ':', 19,
        '|', 23,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(15);
      if (('A' <= lookahead && lookahead <= 'G')) ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_song_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_frontmatter_delimiter);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_frontmatter_key);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_frontmatter_value);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_frontmatter_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_barline);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_note_letter);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_accidental);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_quality);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_quality);
      if (lookahead == '7') ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_quality);
      if (lookahead == '7') ADVANCE(33);
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_quality);
      if (lookahead == 'b') ADVANCE(7);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_quality);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 14},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_song_token1] = ACTIONS(1),
    [sym_frontmatter_delimiter] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_barline] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_note_letter] = ACTIONS(1),
    [sym_accidental] = ACTIONS(1),
    [sym_quality] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_song] = STATE(20),
    [sym_frontmatter] = STATE(4),
    [sym_row] = STATE(4),
    [aux_sym_song_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_song_token1] = ACTIONS(5),
    [sym_frontmatter_delimiter] = ACTIONS(7),
    [sym_barline] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_note_letter,
    STATE(15), 1,
      sym_time_signature,
    STATE(21), 1,
      sym_chord,
    STATE(3), 2,
      sym_bar_tail,
      aux_sym_row_repeat1,
    ACTIONS(11), 4,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      sym_frontmatter_delimiter,
      sym_barline,
  [23] = 6,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(22), 1,
      sym_note_letter,
    STATE(15), 1,
      sym_time_signature,
    STATE(21), 1,
      sym_chord,
    STATE(3), 2,
      sym_bar_tail,
      aux_sym_row_repeat1,
    ACTIONS(17), 4,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      sym_frontmatter_delimiter,
      sym_barline,
  [46] = 5,
    ACTIONS(7), 1,
      sym_frontmatter_delimiter,
    ACTIONS(9), 1,
      sym_barline,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      aux_sym_song_token1,
    STATE(5), 3,
      sym_frontmatter,
      sym_row,
      aux_sym_song_repeat1,
  [64] = 5,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      aux_sym_song_token1,
    ACTIONS(34), 1,
      sym_frontmatter_delimiter,
    ACTIONS(37), 1,
      sym_barline,
    STATE(5), 3,
      sym_frontmatter,
      sym_row,
      aux_sym_song_repeat1,
  [82] = 5,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_note_letter,
    STATE(15), 1,
      sym_time_signature,
    STATE(21), 1,
      sym_chord,
    STATE(2), 2,
      sym_bar_tail,
      aux_sym_row_repeat1,
  [99] = 1,
    ACTIONS(40), 6,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      sym_frontmatter_delimiter,
      sym_barline,
      anon_sym_LPAREN,
      sym_note_letter,
  [108] = 1,
    ACTIONS(42), 6,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      sym_frontmatter_delimiter,
      sym_barline,
      anon_sym_LPAREN,
      sym_note_letter,
  [117] = 3,
    ACTIONS(44), 1,
      sym_frontmatter_delimiter,
    ACTIONS(46), 1,
      sym_frontmatter_key,
    STATE(11), 2,
      sym_frontmatter_field,
      aux_sym_frontmatter_repeat1,
  [128] = 1,
    ACTIONS(48), 4,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      sym_frontmatter_delimiter,
      sym_barline,
  [135] = 3,
    ACTIONS(46), 1,
      sym_frontmatter_key,
    ACTIONS(50), 1,
      sym_frontmatter_delimiter,
    STATE(12), 2,
      sym_frontmatter_field,
      aux_sym_frontmatter_repeat1,
  [146] = 3,
    ACTIONS(52), 1,
      sym_frontmatter_delimiter,
    ACTIONS(54), 1,
      sym_frontmatter_key,
    STATE(12), 2,
      sym_frontmatter_field,
      aux_sym_frontmatter_repeat1,
  [157] = 1,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      aux_sym_song_token1,
      sym_frontmatter_delimiter,
      sym_barline,
  [164] = 3,
    ACTIONS(59), 1,
      sym_barline,
    ACTIONS(61), 1,
      sym_accidental,
    ACTIONS(63), 1,
      sym_quality,
  [174] = 2,
    ACTIONS(15), 1,
      sym_note_letter,
    STATE(24), 1,
      sym_chord,
  [181] = 2,
    ACTIONS(65), 1,
      sym_barline,
    ACTIONS(67), 1,
      sym_quality,
  [188] = 1,
    ACTIONS(69), 2,
      sym_frontmatter_delimiter,
      sym_frontmatter_key,
  [193] = 1,
    ACTIONS(71), 1,
      anon_sym_COLON,
  [197] = 1,
    ACTIONS(73), 1,
      sym_integer,
  [201] = 1,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
  [205] = 1,
    ACTIONS(77), 1,
      sym_barline,
  [209] = 1,
    ACTIONS(65), 1,
      sym_barline,
  [213] = 1,
    ACTIONS(79), 1,
      anon_sym_SLASH,
  [217] = 1,
    ACTIONS(81), 1,
      sym_barline,
  [221] = 1,
    ACTIONS(83), 1,
      aux_sym_song_token1,
  [225] = 1,
    ACTIONS(85), 1,
      sym_integer,
  [229] = 1,
    ACTIONS(87), 1,
      sym_barline,
  [233] = 1,
    ACTIONS(89), 1,
      sym_frontmatter_value,
  [237] = 1,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
  [241] = 1,
    ACTIONS(93), 1,
      sym_note_letter,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 64,
  [SMALL_STATE(6)] = 82,
  [SMALL_STATE(7)] = 99,
  [SMALL_STATE(8)] = 108,
  [SMALL_STATE(9)] = 117,
  [SMALL_STATE(10)] = 128,
  [SMALL_STATE(11)] = 135,
  [SMALL_STATE(12)] = 146,
  [SMALL_STATE(13)] = 157,
  [SMALL_STATE(14)] = 164,
  [SMALL_STATE(15)] = 174,
  [SMALL_STATE(16)] = 181,
  [SMALL_STATE(17)] = 188,
  [SMALL_STATE(18)] = 193,
  [SMALL_STATE(19)] = 197,
  [SMALL_STATE(20)] = 201,
  [SMALL_STATE(21)] = 205,
  [SMALL_STATE(22)] = 209,
  [SMALL_STATE(23)] = 213,
  [SMALL_STATE(24)] = 217,
  [SMALL_STATE(25)] = 221,
  [SMALL_STATE(26)] = 225,
  [SMALL_STATE(27)] = 229,
  [SMALL_STATE(28)] = 233,
  [SMALL_STATE(29)] = 237,
  [SMALL_STATE(30)] = 241,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_song, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_song, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_song_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_song_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_song_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_song_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bar_tail, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bar_tail, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_frontmatter_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_frontmatter_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter_field, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [75] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_signature, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_grigson(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
